# Defines a Kubernetes Service that exposes the 'api-service' application to external traffic.
# The service is of type LoadBalancer, which allocates an external IP to route traffic to the service.

apiVersion: v1
kind: Service
metadata:
  name: api-service-service         # Name of the Service
spec:
  type: LoadBalancer                # Type of the Service (LoadBalancer)
  selector:
    app: api-service                # Selector to match pods labeled with 'app: api-service'
  ports:
  - port: 80                        # Port exposed by the Service
    targetPort: 5000                # Port on pods to which traffic is forwarded
