# Defines a Kubernetes Secret named 'postgres-secrets' containing sensitive data for PostgreSQL authentication.

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets             # Name of the Secret
type: Opaque                         # Type of Secret (Opaque, indicating arbitrary data)
data:
  POSTGRES_USER: dXNlcg==            # Base64-encoded PostgreSQL username
  POSTGRES_PASSWORD: cGFzc3dvcmQ=    # Base64-encoded PostgreSQL password
